workflows:
  version: 2  
  build_and_test:
    jobs:
      - build_test

jobs:
  build_test:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
        name: install the npm package
        command: npm install
      - run:
          #Add command name and bash commands to execute
        name: Build the project 
        command: npm build
      - run:
    #Add command name and bash commands to execute
        name: Run test
        command: npm test
