
jobs:
  build_test:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install npm package
          command: npm install
      - run:
          name: Build the project 
          command: npm build
      - run:
          name: Run test
          command: npm test
  deploy:
    working_directory: ~/project
    docker:
    - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Deployment
          command: echo "SUCCESS - App deployment completed"

workflows:
  version: 2  
  build_and_test:
    jobs:
      - build_test
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
            - build_test
      - deploy:
          requires:
            - hold
