version: 2  

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          #Add command name and bash commands to execute
          name: Enter command description
          command: echo "Add command here"